name: RSS Ingest (Twice Daily)

on:
  schedule:
    - cron: '35 9 * * *'  # 10:35 CET/CEST approx
    - cron: '35 17 * * *' # 18:35 CET/CEST approx
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RSS ingest (limit=1)
        env:
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          BASE_URL: ${{ secrets.INGEST_BASE_URL || 'https://dinelportal.dk' }}
        run: |
          set -euo pipefail
          URL="$BASE_URL/api/news/ingest?limit=1&minWords=1200&llm=openai"
          echo "Calling: $URL"
          curl -fsS -H "x-admin-secret: $ADMIN_SECRET" "$URL"

