name: RSS Ingest (Twice Daily)

on:
  schedule:
    - cron: '35 9 * * *'  # 10:35 CET/CEST approx
    - cron: '35 17 * * *' # 18:35 CET/CEST approx
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        env:
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          BASE_URL: ${{ secrets.INGEST_BASE_URL || 'https://dinelportal.dk' }}
          RSS_INGEST_URL: ${{ secrets.RSS_INGEST_URL }}
        run: |
          set -euo pipefail
          if [ -z "${ADMIN_SECRET:-}" ]; then
            echo "Missing GitHub secret ADMIN_SECRET. Set it in repo or org secrets to match the production Vercel env var ADMIN_SECRET." >&2
            exit 1
          fi
          if [ -z "${BASE_URL:-}" ]; then
            echo "BASE_URL is empty; set secrets.INGEST_BASE_URL or rely on default." >&2
            exit 1
          fi

      - name: Trigger RSS ingest (limit=1)
        env:
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          BASE_URL: ${{ secrets.INGEST_BASE_URL || 'https://dinelportal.dk' }}
          RSS_INGEST_URL: ${{ secrets.RSS_INGEST_URL }}
        run: |
          set -euo pipefail
          # Prefer explicit RSS_INGEST_URL if present; otherwise, use BASE_URL + default path
          if [ -n "${RSS_INGEST_URL:-}" ]; then
            URL="$RSS_INGEST_URL"
          else
            URL="$BASE_URL/api/news/ingest?limit=1&minWords=1200&llm=openai"
          fi
          FALLBACK_URL="$BASE_URL/api/news/ingest?limit=1&minWords=1200&llm=openai"
          echo "Calling: $URL"
          TMP_RESP="$(mktemp)"
          STATUS=$(curl -sS \
            --retry 3 --retry-delay 5 --max-time 300 \
            -H "x-admin-secret: $ADMIN_SECRET" \
            -H "User-Agent: gha-rss-ingest/1.0" \
            -o "$TMP_RESP" -w "%{http_code}" \
            "$URL" || true)
          echo "HTTP $STATUS"
          if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 300 ]; then
            cat "$TMP_RESP"
            exit 0
          fi
          echo "Primary URL failed (status=$STATUS). Response body:" >&2
          cat "$TMP_RESP" >&2 || true
          echo "Falling back to default endpoint: $FALLBACK_URL" >&2
          TMP2="$(mktemp)"
          STATUS2=$(curl -sS \
            --retry 2 --retry-delay 5 --max-time 300 \
            -H "x-admin-secret: $ADMIN_SECRET" \
            -H "User-Agent: gha-rss-ingest/1.0 (fallback)" \
            -o "$TMP2" -w "%{http_code}" \
            "$FALLBACK_URL" || true)
          echo "Fallback HTTP $STATUS2"
          if [ "$STATUS2" -ge 200 ] && [ "$STATUS2" -lt 300 ]; then
            cat "$TMP2"
            exit 0
          fi
          echo "Fallback failed. Response body:" >&2
          cat "$TMP2" >&2 || true
          if [ "$STATUS2" = "403" ]; then
            echo "Hint: 403 Forbidden usually means the x-admin-secret header does not match the server's ADMIN_SECRET or production ingestion is disabled (INGEST_ALLOW_PROD!=true)." >&2
          fi
          exit 1
